/*******************************************
* EasyCast MediaServer - Browser FR trans. *
* Copyright: UbiCast, all rights reserved  *
* Author: Stephane Diemer                  *
*******************************************/

utils.add_translations({
    "Loading": "Chargement",
    "Channels list": "Liste des chaînes",
    "Search": "Rechercher",
    "Search results": "Résultats de la recherche",
    "Search:": "Rechercher&nbsp;:",
    "Search in:": "Rechercher dans&nbsp;:",
    "Search for:": "Contenu à rechercher&nbsp;:",
    "Search in progress": "Recherche en cours",
    "Go": ">",
    "Use the input in the left column to search for something.": "Utilisez le champ de texte à gauche pour rechercher du contenu.",
    "No results.": "Pas de résultat.",
    "titles": "titres",
    "descriptions": "descriptions",
    "keywords": "mots clés",
    "speakers": "intervenants",
    "companies": "sociétés",
    "chapters": "chapitres",
    "photos": "photos",
    "channels": "chaînes",
    "videos": "vidéos",
    "live streams": "diffusions en direct",
    "photos groups": "groupes de photos",
    "Channel's content": "Contenu de la chaîne",
    "Catalog root": "Racine du catalogue",
    "Channels": "Chaînes",
    "Sub channels": "Sous chaînes",
    "Videos": "Vidéos",
    "Live streams": "Diffusions en direct",
    "Photos groups": "Groupes de photos",
    "channel(s)": "chaîne(s)",
    "video(s)": "vidéo(s)",
    "live stream(s)": "diffusion(s) en direct",
    "photos group(s)": "groupe(s) de photos",
    "No information about media.": "Pas d'information sur le média",
    "Unable to get media's information. Request timed out.": "Impossible d'obtenir les informations sur le média. Délai d'attente de la requête écoulé.",
    "Unable to get media's information because you cannot access to this media.": "Impossible d'obtenir les informations sur le média car vous ne pouvez pas accéder à ce média.",
    "Media does not exist.": "Aucun média ne correspond à l'identifiant entré.",
    "Click to display the content of this channel": "Cliquez pour afficher le le contenu de cette chaîne",
    "Unable to get channel's content. Request timed out.": "Impossible d'obtenir la liste du contenu de la chaîne. Délai d'attente de la requête écoulé.",
    "You are not logged in. Please login in Moodle and retry.": "Vous devez vous authentifier pour voir les médias. Veuillez vous authentifier puis réessayez.",
    "Unable to get channel's content because you cannot access to this channel.": "Impossible d'obtenir la liste du contenu de la chaîne car vous ne disposez pas du droit d'accès à cette chaîne.",
    "Requested channel does not exist.": "La chaîne demandée n'existe pas.",
    "This channel contains no sub channels and no medias.": "Cette chaîne ne contient pas de sous chaîne ni de média.",
    "This channel contains no sub channels.": "Cette chaîne ne contient pas de sous chaîne.",
    "This channel contains no medias.": "Cette chaîne ne contient pas de média.",
    "Accessible for all users": "Accessible pour tous les utilisateurs",
    "Accessible only for authenticated users": "Accessible uniquement pour les utilisateurs authentifiés",
    "Accessible only for authenticated users with access right": "Accessible uniquement pour les utilisateurs authentifiés qui possèdent le droit d'accès",
    "Inaccessible for all users": "Inaccessible pour tous les utilisateurs",
    "Visible for all users": "Visible pour tous les utilisateurs",
    "Visible only for authenticated users": "Visible uniquement pour les utilisateurs authentifiés",
    "Visible only for authenticated users with access right": "Visible uniquement pour les utilisateurs authentifiés qui possèdent le droit d'accès",
    "Invisible for all users": "Invisible pour tous les utilisateurs",
    "This media is published": "Ce média est publié",
    "This media is not published": "Ce média n'est pas publié",
    "This video is not ready": "Cette vidéo n'est pas prête",
    "Select a channel to display its content.": "Sélectionnez une chaîne pour afficher son contenu.",
    "Select a channel": "Sélectionner une chaîne",
    "Select a media": "Sélectionner un média",
    "Select this channel": "Sélectionner cette chaîne",
    "Select this media": "Sélectionner ce média",
    "Display channel": "Afficher cette chaîne",
    "Channel:": "Chaîne&nbsp;:",
    "Current channel": "Chaîne courante",
    "Parent channel:": "Chaîne parente&nbsp;:",
    "Parent channel": "Chaîne parente",
    "January": "janvier",
    "February": "février",
    "March": "mars",
    "April": "avril",
    "May": "mai",
    "June": "juin",
    "July": "juillet",
    "August": "août",
    "September": "septembre",
    "October": "octobre",
    "November": "novembre",
    "December": "décembre",
    "at": "à",
    // tree manager
    "Loading": "Chargement",
    "Unable to get channels tree. Request timed out.": "Impossible d'obtenir la liste des chaînes. Délai d'attente de la requête écoulé.",
    "An error occured during request:": "Une erreur est survenue pendant la requête&nbsp;:",
    "Unable to get channels tree because you are not logged in.": "Impossible d'obtenir la liste des chaînes, vous n'êtes pas authentifié",
    "Unable to get channels tree because you cannot access to this channel.": "Impossible d'obtenir la liste des chaînes, vous n'avez pas la permission pour accéder à cette chaîne.",
    "Channel does not exist.": "La chaîne demandée n'existe pas.",
    "An error occured in medias server. Please try again later.": "Une erreur est suvenue dans le serveur de médias. Veuillez réessayer plus tard.",
    "No information about error.": "Aucune information sur l'erreur."
}, "fr");

